### ISSUE TITLE
X11 is killed without [signal 9] message.

### ISSUE THREAD

**Issue by chopin** [phoenixbyrd/Termux_XFCE#16]
Hi again.

After I fixed the problem of [signal 9], I used X11 without sudden death for a while. But, the sudden death started again from some time point later.

The sympton is almost the same to the previous one (called Phantom Process Killer), The only difference is that Termux window is killed without displaying any error message. 

After X11 is killed, "adb devices" shows "no device connected".  Then, I turn off the wireless-debugging option, and turn on again. I run "adb connect[IP]:[PORT]", then I can see a system popup message showing the activation of wireless-debugging. I can see a conneced device by "adb devices".  However, X11 is killed again anyway later. 

I tried to use with/without wireless-debugging, and x11 is killed later in both ways. I feel like Phantom-process-killer is still active. X11 is not killed only when I leave x11 in the background without using it.

Do you have any idea about this problem?

**Comment by chopin** [comment]
When I fixed the [signal 9] problem before, I followed the follwoing web page. But [Feature Flags] in [Setting]/[Developer option] shows empty unlike the web page, so I couldn't do any about the related option "settings_enable_monitor_phantom_procs". However, I completed all the other steps in the webpage. I don't know whether it is related to the problem.
https://docs.andronix.app/android-12/andronix-on-android-12-and-beyond

**Comment by chopin** [comment]
Following is my device information: 
Samsung Galaxy Note 20
OneUI version 5.1
Android version 13.

I apply the three adb commands for OneUI as guided in the webpage whenever I enable wireless-debugging. However, x11 is killed for a while later usually around tens of minutes to a hour later. X11 is killed more often as I use it heavily, and less often as I use rarely.

I wonder whether it is caused by death of wireless-debugging , or by death of adb connection, or something else.

**Comment by phoenixbyrd** [comment]
Sounds like the phantom process issue wasn't resolved properly if there were steps that weren't completed. I would use either LADB app or follow youtube video linked in this github

**Comment by chopin** [comment]
> ... I would use either LADB app or follow youtube video linked in this github

Is LADB different from adb installed by apt-get? My current adb (installed by apt-get) runs fine though still the sudden death problem. Does it worth trying LADB?
 
I found that the Dex desktop manager with Termux is killed together when X11 is killed, and that is why I don't see [signal 9] message before the death. 

I don't understand why the DEX desktop manager is killed if Phantom Process Killer is the cause. In my understanding, Phantom Process Killer kills only application processes, not system processes such as the Dex desktop manager.

**Comment by chopin** [comment]
I found that excessive CPU usage could kill the process. It seems that the disabling Phantom Process Killer does not change the excessive CPU killing.

I remember that X11 was killed pretty often when I heavily used 3D graphics using WebGpu (I am developing a web app in 3D graphics). But, opening many web pages and leaving background didn't kill X11.

https://github.com/agnostic-apollo/Android-Docs/blob/master/en/docs/apps/processes/phantom-cached-and-empty-processes.md#excessive-cpu

**Comment by chopin** [comment]
I found that Android was killing apps with high cpu usage to save battery life. It is serious in a Samsung phone .

 It is not the case of Phatom Process Killer killing a process with over 35 subprocesses. My Termux-XFCE has over 100 subprocesses, but not it is not killed as long as I don't use heavilly.  But, it is killed when I use cpu heavily with a single webpage running 3D graphics heavily.

The number of process is not related in Battery-Life-Killer. You can disable it by turning off the baterry management option in application setting as following link:

https://www.howtogeek.com/762936/how-to-stop-android-from-killing-background-apps/

**Comment by chopin** [comment]
Still, Termux-x11 is killed by excessive CPU usage. The battery-life-killer setting above has no effect.

**Comment by romanovj** [comment]
> Still, Termux-x11 is killed by excessive CPU usage. The battery-life-killer setting above has no effect.

what do you have here?

adb shell dumpsys activity exit-info com.termux.x11

**Comment by chopin** [comment]
```
> adb shell dumpsys activity exit-info com.termux.x11

ACTIVITY MANAGER PROCESS EXIT INFO (dumpsys activity exit-info)
Last Timestamp of Persistence Into Persistent Storage: 2023-10-01 20:56:26.572
  package: com.termux.x11
    Historical Process Exit for uid=10383
        ApplicationExitInfo #0:
          timestamp=2023-10-01 19:00:07.413 pid=10156 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=3 (LOW_MEMORY) subreason=0 (UNKNOWN) status=0
          importance=100 pss=70MB rss=93MB description=null state=empty trace=null
        ApplicationExitInfo #1:
          timestamp=2023-10-01 17:50:34.789 pid=20019 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=3 (LOW_MEMORY) subreason=0 (UNKNOWN) status=0
          importance=100 pss=65MB rss=82MB description=null state=empty trace=null
        ApplicationExitInfo #2:
          timestamp=2023-10-01 15:41:15.393 pid=14031 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=3 (LOW_MEMORY) subreason=0 (UNKNOWN) status=0
          importance=100 pss=56MB rss=44MB description=null state=empty trace=null
        ApplicationExitInfo #3:
          timestamp=2023-10-01 15:36:52.461 pid=21702 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=3 (LOW_MEMORY) subreason=0 (UNKNOWN) status=0
          importance=100 pss=71MB rss=101MB description=null state=empty trace=null
        ApplicationExitInfo #4:
          timestamp=2023-09-30 12:22:17.340 pid=21096 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=3 (LOW_MEMORY) subreason=0 (UNKNOWN) status=0
          importance=100 pss=62MB rss=61MB description=null state=empty trace=null
        ApplicationExitInfo #5:
          timestamp=2023-09-30 12:14:29.978 pid=15983 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=3 (LOW_MEMORY) subreason=0 (UNKNOWN) status=0
          importance=100 pss=70MB rss=110MB description=null state=empty trace=null
        ApplicationExitInfo #6:
          timestamp=2023-09-30 00:33:35.918 pid=22666 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=3 (LOW_MEMORY) subreason=0 (UNKNOWN) status=0
          importance=100 pss=67MB rss=46MB description=null state=empty trace=null
        ApplicationExitInfo #7:
          timestamp=2023-09-30 00:24:13.987 pid=21673 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=13 (OTHER KILLS BY SYSTEM) subreason=2 (TOO MANY CACHED PROCS) status=0
          importance=400 pss=45MB rss=114MB description=too many cached state=empty trace=null
        ApplicationExitInfo #8:
          timestamp=2023-09-30 00:22:42.657 pid=18697 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=13 (OTHER KILLS BY SYSTEM) subreason=2 (TOO MANY CACHED PROCS) status=0
          importance=400 pss=62MB rss=128MB description=too many cached state=empty trace=null
        ApplicationExitInfo #9:
          timestamp=2023-09-30 00:19:28.447 pid=5784 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=13 (OTHER KILLS BY SYSTEM) subreason=2 (TOO MANY CACHED PROCS) status=0
          importance=400 pss=52MB rss=82MB description=too many cached state=empty trace=null
        ApplicationExitInfo #10:
          timestamp=2023-09-30 00:04:31.154 pid=13941 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=13 (OTHER KILLS BY SYSTEM) subreason=0 (UNKNOWN) status=0
          importance=400 pss=51MB rss=114MB description=proc_dex_display_disabled(2,2) state=empty trace=null
        ApplicationExitInfo #11:
          timestamp=2023-09-29 23:41:00.713 pid=19786 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=3 (LOW_MEMORY) subreason=0 (UNKNOWN) status=0
          importance=400 pss=31MB rss=82MB description=null state=empty trace=null
        ApplicationExitInfo #12:
          timestamp=2023-09-29 17:39:36.314 pid=10852 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=3 (LOW_MEMORY) subreason=0 (UNKNOWN) status=0
          importance=400 pss=56MB rss=67MB description=null state=empty trace=null
        ApplicationExitInfo #13:
          timestamp=2023-09-29 17:17:11.978 pid=26376 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=3 (LOW_MEMORY) subreason=0 (UNKNOWN) status=0
          importance=100 pss=66MB rss=86MB description=null state=empty trace=null
        ApplicationExitInfo #14:
          timestamp=2023-09-29 15:46:09.342 pid=29625 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=3 (LOW_MEMORY) subreason=0 (UNKNOWN) status=0
          importance=400 pss=26MB rss=41MB description=null state=empty trace=null
        ApplicationExitInfo #15:
          timestamp=2023-09-29 14:46:22.608 pid=7372 realUid=10383 packageUid=10383 definingUid=10383 user=0
          process=com.termux.x11 reason=3 (LOW_MEMORY) subreason=0 (UNKNOWN) status=0
          importance=100 pss=53MB rss=58MB description=null state=empty trace=null

```

**Comment by romanovj** [comment]
```
adb shell
#then
device_config set_sync_disabled_for_tests persistent
device_config put activity_manager max_cached_processes 128
device_config put activity_manager use_oom_re_ranking true
device_config put activity_manager imperceptible_kill_exempt_packages com.termux.x11
```

**Comment by chopin** [comment]
I executed the command lines you commented. And, it is not killed anymore! Wow. I am so happy now! I am doing stress test in my phone, and it is not killed until I run and load a lot intensively on my web browser. I think that I will be able to work using my phone without worrying about being killed from now.

THANK YOU SO MUCH romanovj!

**Comment by chopin** [comment]
The low memory killing is significantly minimized further by changing Ram Plus in Android setting:

Setting -> Device Care -> Memory -> Ram Plus -> 8GB
